# Site
name: 'Olcay Soyuhan'
description: ""
logo: ''
favicon: 'assets/images/favicon.ico'
baseurl: ''
disqus: 'olcay-s'
email: ''
google_verify: 04jnirQhgDnZjZjWk0IfPIL1vxKhksIxlMG7T_dxdtQ"

# Google Analytics key, leave blank to ignore
google_analytics_key:

include: ["_pages"]
permalink: /:title/

authors:
  olcay:
    name: Olcay
    site:           
    avatar:         
    bio:            
    email:          
    twitter:        

# Defaults
defaults:
  - jekyll-feed
  - jekyll-sitemap

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-feed
  - jekyll-sitemap


  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: 
      avatar: 
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
